[package]
name = "poc-framework"
version = "0.1.2"
authors = []
edition = "2018"
repository = "https://github.com/neodyme-labs/solana-poc-framework"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["solana", "smart", "contracts"]
description = "A framework for creating PoC's for Solana Smart Contracts in a painless and intuitive way"

[dependencies]
itertools = "0.10.1"
bincode = "1.3.3"
rand = "0.7.3"
tempfile = "3.2.0"
borsh = "0.9.1"
solana-sdk = "1.8.2"
solana-program = "1.8.2"
solana-logger = "1.8.2"
solana-runtime = "1.8.2"
solana-transaction-status = "1.8.2"
solana-cli-output = "1.8.2"
solana-bpf-loader-program = "1.8.2"
solana-client = "1.8.2"
solana-faucet = "1.8.2"
spl-token = "3.1.0"
spl-memo = "3.0.1"
spl-associated-token-account = "1.0.3"
serde = "1.0.125"
sha2 = "0.9.5"
