[package]
name = "poc-framework"
version = "0.1.0"
authors = []
edition = "2018"


[dependencies]
itertools = "0.10.1"
bincode = "1.3.3"
rand = "0.7.3"
tempfile = "3.2.0"
borsh = "0.9.1"
solana-sdk = "1.7.10"
solana-program = "1.7.10"
solana-logger = "1.7.10"
solana-runtime = "1.7.10"
solana-transaction-status = "1.7.10"
solana-cli-output = "1.7.10"
solana-bpf-loader-program = "1.7.10"
solana-client = "1.7.10"
solana-faucet = "1.7.10"
spl-token = "3.2.0"
spl-memo = "3.0.1"
spl-associated-token-account = "1.0.3"
serde = "1.0.125"
sha2 = "0.9.5"
